--- THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT MANUALLY.

---@class battle_alliance
local battle_alliance = {}

--- Creates and returns a battle_armies object listing all armies in the alliance.
---@return battle_armies #armies list 
function battle_alliance:armies() end

--- Forces any AI in this alliance to prioritise attacking behaviour.
function battle_alliance:force_ai_plan_type_attack() end

--- Returns whether this alliance is attacking in the battle.
---@return boolean #is attacker 
function battle_alliance:is_attacker() end

--- Forces any AI in this alliance to prioritise defensive behaviour.
function battle_alliance:force_ai_plan_type_defend() end

--- Creates and returns an ai_planner object attached to this alliance. Consider creating a script_ai_planner instead of calling this function directly.
---@return ai_planner #ai planner 
function battle_alliance:create_ai_unit_planner() end

--- Immediately forces victory for this alliance.
function battle_alliance:force_battle_victory() end
